### PR TITLE
Poll in progress functionality

### LINKED ISSUE #23: Add present poll functionality
API calls should be mocked at this stage.

### PR DESCRIPTION
**Pull request by Goff-Davis**
This does not keep track of each questions state, but everything else mentioned in the sponsor meeting is included.

- [x] Ability to navigate between questions
- [x] Ability to navigate between different stages of a question
- [x] Remove close question stage
~~Keep track of state of each question~~
- [x] Make the "next" button say what the next state is
- [x] Make percentage bar fill question instead of being on the side

WIP to make suggested design changes

Fix #23

### CODE REVIEW

**Comment by ljoks** [comment]
I like that we have an indication for the question being closed for submissions, however I think that we should still be able to see the question/answer choices during this step. The professor may want to discuss details about the question before moving on to show the results

**Comment by ljoks** [comment]
Also bug: 
- the `Exit` button in the header doesn't work UNLESS you are on the very last step where `End Session` is also an available button. 
- if you use the `Exit` button at this time, then present again, you start at the end of the session. The session state is not being reset back to the beginning

**Comment by Goff-Davis** [comment]
Ready for re review minus whether to add a back button

**Review by weining-li — APPROVED** [review]
I mean I didn't read through all the code but everything seems to work :cake:

**Comment by Goff-Davis** [comment]
The blue breadcrumbs were Ryan's idea. Not sure if I like them but I agree they shouldn't be yellow, so 🤷

**Review by weining-li — APPROVED** [review]
Fix long answer choices going out the screen. Looks good otherwise

**Review by weining-li — APPROVED** [review]

**Pull request merged**
