### PR TITLE
Home Skeleton

### LINKED ISSUE #13: Home screen skeleton

### PR DESCRIPTION
**Pull request by kennygperez**
Fixed #13

### CODE REVIEW

**Review by Goff-Davis — APPROVED** [review]
Looks good to me.

Is there a way to manually set the state so that both branches can be viewed? There's also still that android bug with navigation. Neither of these things are worth blocking merging though.

**Comment by kennygperez** [comment]
@Goff-Davis remember that its just an emulator bug its works fine the android phone Ryan gave me

**Comment by kennygperez** [comment]
But I do have a plan if it continues to be an issue to switch to the tab navigator

**Comment by Goff-Davis** [comment]
> @Goff-Davis remember that its just an emulator bug its works fine the android phone Ryan gave me

Oh nice, I didn't know that was the case. Sounds good then

**Pull request merged**
