### PR TITLE
Feature/mobile structure

### PR DESCRIPTION
**Pull request by kennygperez**

### CODE REVIEW

**Comment by kennygperez** [comment]
Fixed #16

**Comment by kennygperez** [comment]
and fixes #12

**Comment by Goff-Davis** [comment]
The code looks good to me. I found a potential issue with routing from the Polls screen on Android.

1. Open the drawer and select Settings
2. Open the drawer again and select Polls

After doing this you will no longer be able to open the drawer again and clicking the HOME button on the Polls screen doesn't do anything either.

**Comment by kennygperez** [comment]
That's wild ill try to run the emulator to see what's up with it, thank you for the feedback

**Comment by kennygperez** [comment]
I need an Android phone

**Comment by kennygperez** [comment]
I got a phone from Ryan going to see and hope its just an emulator issue

**Comment by kennygperez** [comment]
@Goff-Davis this works on the Android phone that Ryan gave me
I think it may be an issue with the emulator

**Review by weining-li — APPROVED** [review]

**Pull request merged**
