### PR TITLE
Added question locking

### PR DESCRIPTION
**Pull request by kennygperez**

### CODE REVIEW

**Review by Goff-Davis — DISMISSED** [review]
Looks good, but give ryan a few minutes to respond before you merge, just in case

**Comment by kennygperez** [comment]
> Looks good, but give Ryan a few minutes to respond before you merge, just in case

Will do!

**Review by weining-li — DISMISSED** [review]
i guess

**Comment by kennygperez** [comment]
Screen Shot 2021-04-20 at 12 23 49 PM

**Review by ljoks — APPROVED** [review]
lgtm

**Pull request merged**
