### PR TITLE
Feature/frontend updates

### LINKED ISSUE #76: Add individual session screens for gradebook
clicking on a session brings you to a whole other table just for that session

### PR DESCRIPTION
**Pull request by weining-li**
Resolves #76 
and part of #78

### CODE REVIEW

**Review by Goff-Davis — CHANGES_REQUESTED** [review]
Good improvements here. A few of things:

**For the home page:**

1. The `present` button should not show up in the question preview.
2. The question preview and the buttons in the question preview need to be larger. We should shoot for the smallest body font to be `16px`. Currently the "base" font is `14px` with the "large" font being `1rem` (which is `16px`). The `14px` fonts can be upped to `16px` and the `16px` can probably go up to `20px`.
3. The text in the sidebar do not have a specified font size. This can make it look inconsistent across browsers.

**For the gradebook:**

The design looks good, no issues there. However the navigation to and from a session's info should make use of the react router.

This pr doesn't cover most of the design changes we talked about yesterday. Are you intending to keep working on the rest?

**Comment by weining-li** [comment]
yeah im gonna make a separate PR for the other homepage changes

**Comment by Goff-Davis** [comment]
Ah ok cool. In that case the only real thing for me to bring up is using the router to get the session's info in the gradebook. E.g. `/gradebook/<sessionId>`

**Review by Goff-Davis — APPROVED** [review]
The gradebook changes look good to me. It looks like this closes #76 and #78? I'd like to get this merged in and then a separate pr for the rest of the changes then

**Comment by weining-li** [comment]
only #76  cuz i haven't changed the viewport CSS for some of the other components

**Pull request merged**
