### PR TITLE
Feature/frontend structure

### PR DESCRIPTION
**Pull request by Goff-Davis**
Since the structure is done, lets get this merged in.

### CODE REVIEW

**Review by ljoks — COMMENTED** [review]
There's obviously way too much to review here all at once but i think a glaring issue is the modals being a route. Idk if you wanted to do that @Goff-Davis otherwise I can try to tackle it in between websocket stuff before we merge this into main

**Comment by Goff-Davis** [comment]
> There's obviously way too much to review here all at once but i think a glaring issue is the modals being a route. Idk if you wanted to do that @Goff-Davis otherwise I can try to tackle it in between websocket stuff before we merge this into main

It's a bit weird since weining's pr has the old modal stuff. It might be better to merge his stuff to this branch (when it's ready)
 and then fix the modal? I don't mind doing it.

**Comment by ljoks** [comment]
ok yeah that single pr is taking way too long, it needs to be broken up into smaller pieces so things can get merged in one at a time instead of all at once

**Comment by Goff-Davis** [comment]
In the future yeah. The idea was supposed to be one ticket = one pr. That big pr is close enough to ready to merge in that I don't know if it's worth it to break up anymore though.

**Review by weining-li — APPROVED** [review]
:cake:

**Pull request merged**
